changelog:
  categories:
    - title: New Features✅
      labels:
          - "*"
    - title: Improved💜
      labels:
            - "*"
    - title: Bugfixes 🎉
      labels:
          - "*"
    - title: Breaking Changes 🛠
      labels:
          - "*"
    - title: Other Changes
      labels:
          - "*"
    - title: Dependencies
      labels:
          - "*"
    
