name: API Reference Synch

on: 
  workflow_dispatch:
    inputs:
      readme-visibility:
        description: "Enter 'draft' to update the API Reference docs hidden for review OR 'public' to update the PUBLIC API Reference official docs"
        required: true
        default: "draft"

  #release:
  #  types: [released]

jobs:
  api-readme-synch:
    name: "API Readme Synch"
    runs-on: ubuntu-latest
    env:
      README_API_SPEC_ID: ${{ github.event.inputs.readme-visibility == 'draft' && secrets.README_API_DRAFT_ID || secrets.README_API_PUBLIC_ID }}
      README_API_VERSION: ${{ github.event.inputs.readme-visibility == 'draft' && secrets.README_API_DRAFT_VERSION || secrets.README_API_PUBLIC_VERSION }}

    steps:   
      - name: Repo Checkout
        uses: actions/checkout@v2
      
      #- name: Fetching OpenAPI spec
      #  run: |
      #    curl -o .github/openapi.json --location --request GET ${{ secrets.PARTNER_API_V2 }}

      - name: Update readme API Reference
        uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: '${{ secrets.README_API_KEY }}:${{ env.README_API_SPEC_ID }}'
          oas-file-path: '.github/openapi.json'
          api-version: ${{ env.README_API_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Release Notes Content Generation
        run: |
          python .github/api_readme_synch.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_URL: ${{ github.api_url }}
          GITHUB_REPO_PATH: ${{ github.repository }}
          README_API_KEY: ${{ secrets.README_API_KEY }}
          README_URL: ${{ secrets.README_URL }}
          API_DREAM_TEAM: ${{ secrets.API_DREAM_TEAM }}
          
          