name: Generate Changelog MD file
on:
  release:
    types: [created, edited]
  
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: BobAnkh/auto-generate-changelog@master
        with:
          REPO_NAME: ''
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH: '.github/CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): Updating changelog content'
          TYPE: 'feat:Feature,fix:Bug Fixes '
          BRANCH: ''
          PULL_REQUEST: ''
          DEFAULT_SCOPE: general
          SUPPRESS_UNSCOPED: false
      
      - name: "Fast echo"
        run: |
          cat .github/CHANGELOG.md