name: Actions Debugging Scripts
on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # GIT_LOG=$(git log --pretty=oneline --format='%s %h' | head -n 1)
      - name: "Fast echo"
        run: |
          GIT_LOG="Commit Msg with () parenthesis inside"    
          REPO_NAME=`echo ${{ github.repository }} | sed 's/.*\///'`
          echo "CLOUD_MSG=`echo $GIT_LOG $REPO_NAME`" >> $GITHUB_ENV
      
      - name: "Checks"
        run: |
          WORKAROUND=${{ env.CLOUD_MSG }}
          echo $WORKAROUND
          
      - run: echo "${{ env.CLOUD_MSG }}"