name: Actions Debugging Scripts
on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    outputs:
      parsed-msg: ${{ steps.py-script.outputs.parsed-msg }}

    steps:
      - uses: actions/checkout@v3

      - name: Python Script
        id: py-script
        run: |
          python .github/workflows/scripts/debug.py
        env: 
          GITHUB_REPO_PATH: ${{ github.repository }}
  
  marco-polo:
    runs-on: ubuntu-latest
    needs: [hello-world]
    steps:
      - name: Script Output in another Job
        run: |
          REPO_NAME=`echo ${{ github.repository }} | sed 's/.*\///'`
          COMMIT_REF=`echo "${{needs.prepare-deployment-matrix.outputs.parsed-msg}} $REPO_NAME"`
          echo "${{needs.hello-world.outputs.py-script}}"

          
      