name: Auto Release Notes

on:
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set Env Variables
        run: |
          echo "PRERELEASE_VERSION=$(echo v`date +%Y.%m.%d`.`git rev-parse --short HEAD`.rc)" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(echo `date +%Y\.%m\.%d`)" >> $GITHUB_ENV
          echo "ESCAPED_REPO=$(echo ${{ github.repository }} | sed 's|\/|\\\/|g')" >> $GITHUB_ENV
          echo "Git status"
          echo "-------------------------------------------------"
          git fetch origin
          git branch
          echo "-------------------------------------------------"
          git log $(git branch --show-current)...origin/master --pretty=oneline --format='* %C(auto) %h %s' >> .github/commits_msgs.txt

      - name: Checking files
        run: |
          echo "-------------------------------------------------"
          cd .github
          ls -al
          cat .github/commits_msgs.txt
          echo "-------------------------------------------------"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.PRERELEASE_VERSION }}
          prerelease: true
          title: ${{ env.PRERELEASE_VERSION }}
      
      - name: "Updating Release Notes MD File"
        continue-on-error: false
        run: |
          sed -i '/#### New Features ✅/r .github/commits_msgs.txt' .github/release_notes_template.md

          perl -pi -w -e 's/{RELEASE_DATE}/${{ env.RELEASE_DATE }}/g;' -e 's/{RELEASE_TAG}/${{ env.PRERELEASE_VERSION }}/g;' \
          -e 's/{GIT_REPO}/${{ env.ESCAPED_REPO }}/g;' .github/release_notes_tmp.md

      - name: "Fetching Release GitHub ID and Updating Local Release Notes"
        continue-on-error: true
        run: |
          curl -o .github/current_release.json --location --request GET https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.PRERELEASE_VERSION }} \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          
          echo "RELEASE_GIT_ID=$(grep --max-count=1 '"id":.*' .github/current_release.json | sed -n 's/[^0-9]*//gp')" >> $GITHUB_ENV

      - name: "Updating Remote Release Notes"
        continue-on-error: true
        run: |
          curl --location --request PATCH https://api.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_GIT_ID }} \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw "{\"tag_name\" : \"${{ env.PRERELEASE_VERSION }}\",\"body\": \"$(perl -p -e 's/\n/\\n/' .github/release_notes_tmp.md)\"}"

